DROP TABLE people IF EXISTS;

CREATE TABLE people  (
  person_id BIGINT IDENTITY NOT NULL PRIMARY KEY,
  first_name VARCHAR(20),
  last_name VARCHAR(20)
);

DROP TABLE user IF EXISTS;
CREATE TABLE  user (
  id BIGINT IDENTITY NOT NULL PRIMARY KEY,
  name varchar(45)
);